### PR TITLE
add: binary

### PR DESCRIPTION
**Pull request by joshgoebel**

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Review by ErikSchierboom — COMMENTED** [review]
Most tracks have deprecated this exercise in favor of the all-your-base exercise, as we used to have separate `octal`/`hexadecimal`/`binary` exercise, but `all-your-base` makes it a generic exercise.

**Comment by joshgoebel** [comment]
Now you tell me, LOL. :-)

**Comment by ErikSchierboom** [comment]
Well, I've only now seen this PR :D

**Comment by joshgoebel** [comment]
Touche!

**Pull request merged**
