### PR TITLE
The circular-buffer stub file was not rewritten from javascript to wren

### PR DESCRIPTION
**Pull request by glennj**

### CODE REVIEW

**Comment by joshgoebel** [comment]
This looks great, it's just the last 2 lines I'm wondering about. :-)

---

I'm not sure where we should go with the errors in the stub (if we provide any at all - ah I guess we have to so that the import doesn't crash the VM so the test suite can run...)... In my proof I went with classes:

```
class BufferEmptyError {
  static error { "buffer empty" }
}
```

And return the class itself (not an instance) as the error... I'm going to ask on the Wren discord and see if there are some better conventions here that perhaps we should use (and encourage)... though that still might leave open what we should or shouldn't include in the stub.

If we decide there are "best practices" should we still go with the "simplest thing that barely works" in the stub?  I realize this is the kind of thing that would normally get covered in concepts, but we don't have concept exercises, only practice for Wren.

**Comment by joshgoebel** [comment]
One other, Minesweeper was still JS but I just corrected it.

**Comment by glennj** [comment]
The only error throwing mechanism I see is `Fiber.abort(msg)`, so I wonder if the "hierarchy of Error classes" is something that wren wants us to do at all.

I haven't yet wrapped my head around catching aborts. The Fibers concept is akin to coroutines, and transferring data in and out while using `try` is something I still need to practice.

**Comment by joshgoebel** [comment]
> The only error throwing mechanism I see is Fiber.abort(msg),

Right but `msg` can be any class or instance reference, just just a string.  So for consistency you'd want to use constants for unique errors, not "magic strings"... the tests don't care though since they just care whether the constant's value matches or not.

**Pull request merged**
