### PR TITLE
Add all-your-base exercise

### PR DESCRIPTION
**Pull request by keiravillekode**

### CODE REVIEW

**Comment by glennj** [comment]
@joshgoebel looks like there's an issue building wren in the "Build wren-console" step:
https://github.com/exercism/wren/actions/runs/6704346196/job/18216580197?pr=147#step:5:70

**Comment by keiravillekode** [comment]
Rebased.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Thanks!

**Comment by ErikSchierboom** [comment]
@glennj I've fixed CI in https://github.com/exercism/wren/pull/146

**Comment by joshgoebel** [comment]
> looks like there's an issue building wren in the "Build wren-console" step:

Yeah newer libc added a function that conflicts with naming... I think it's been fixed upstream so we could probably just pull the fix from wren-cli (if it's clean merge), but I don't have time to look into this right now.  Going back to an older release of Ubuntu without older libc was a good temp fix.

**Pull request merged**
