### PR TITLE
Reset difficulties

### PR DESCRIPTION
**Pull request by glennj**
ref #112 

I recommend reviewing the commits separately:
* the first commit just changes the difficulties
* the second one rearranges the order.

### CODE REVIEW

**Comment by glennj** [comment]
```sh
jq -r '.exercises.practice[] | [.slug, .difficulty] | @csv' {bash,javascript,tcl}/config.json \
| awk -F, '
    {sum[$1]+=$2; count[$1]++}
    END {
        PROCINFO["sorted_in"]="@ind_str_asc"
        for (ex in sum) print ex, sum[ex]/count[ex]
    }
' | column -t > average.difficulty 
```
```none
"accumulate"                 5
"acronym"                    2.66667
"affine-cipher"              4.33333
"all-your-base"              3.66667
"allergies"                  4
"alphametics"                6.5
"anagram"                    2
"armstrong-numbers"          2.33333
"atbash-cipher"              5
"bank-account"               3
"beer-song"                  3.66667
"binary"                     4
"binary-search"              5
"binary-search-tree"         6
"bob"                        3.33333
"book-store"                 6.5
"bowling"                    6.33333
"change"                     7
"circular-buffer"            6
"clock"                      3.66667
"collatz-conjecture"         2.66667
"complex-numbers"            3.5
"connect"                    7
"crypto-square"              6
"custom-set"                 5
"darts"                      2.66667
"diamond"                    4
"difference-of-squares"      2.33333
"diffie-hellman"             3.66667
"dnd-character"              2.66667
"dominoes"                   5
"dot-dsl"                    7
"error-handling"             2.5
"etl"                        2.5
"flatten-array"              4
"food-chain"                 4.33333
"forth"                      7
"gigasecond"                 2.33333
"go-counting"                6.5
"grade-school"               4.5
"grains"                     3.33333
"grep"                       5
"hamming"                    2
"hangman"                    9
"hello-world"                1
"hexadecimal"                4
"high-scores"                2.5
"house"                      2.66667
"isbn-verifier"              3.33333
"isogram"                    2.33333
"kindergarten-garden"        4.66667
"knapsack"                   6
"largest-series-product"     4
"leap"                       1.33333
"linked-list"                4.5
"list-ops"                   6
"luhn"                       3.66667
"markdown"                   5
"matching-brackets"          2.66667
"matrix"                     3
"meetup"                     5.33333
"minesweeper"                6
"nth-prime"                  5
"nucleotide-count"           3
"ocr-numbers"                5
"octal"                      4
"palindrome-products"        6.33333
"pangram"                    2.33333
"parallel-letter-frequency"  5
"pascals-triangle"           4
"perfect-numbers"            3
"phone-number"               3
"pig-latin"                  3.66667
"point-mutations"            1
"poker"                      6.66667
"pov"                        8
"prime-factors"              3.33333
"promises"                   6
"protein-translation"        2.33333
"proverb"                    3.33333
"pythagorean-triplet"        5.33333
"queen-attack"               4.66667
"rail-fence-cipher"          5.66667
"raindrops"                  2
"rational-numbers"           4.66667
"react"                      8
"rectangles"                 6.33333
"resistor-color"             1
"resistor-color-duo"         2
"resistor-color-trio"        3.33333
"rest-api"                   6.5
"reverse-string"             1.66667
"rna-transcription"          1.66667
"robot-name"                 4.5
"robot-simulator"            5.33333
"roman-numerals"             3
"rotational-cipher"          2.33333
"run-length-encoding"        3.66667
"saddle-points"              5.5
"satellite"                  6
"say"                        6.33333
"scale-generator"            3.5
"scrabble-score"             3
"secret-handshake"           4
"series"                     2.33333
"sieve"                      3.66667
"simple-cipher"              4.66667
"simple-linked-list"         6
"space-age"                  2.33333
"spiral-matrix"              4.33333
"square-root"                3.33333
"strain"                     3.5
"sublist"                    2.66667
"sum-of-multiples"           3.33333
"tournament"                 4.33333
"transpose"                  3.33333
"triangle"                   2.66667
"trinary"                    4
"twelve-days"                3.33333
"two-bucket"                 6.66667
"two-fer"                    1
"variable-length-quantity"   5
"word-count"                 2.33333
"word-search"                7.5
"wordy"                      5.66667
"yacht"                      4.66667
"zebra-puzzle"               8
"zipper"                     7.5
```

**Comment by joshgoebel** [comment]
Man that re-order is like impossible to review, did you do that using an automated tool or by hand? :)

That script is awesome... could you spit out the standard deviation across tracks also?  That might be interested in dicsuss in a larger context.

**Comment by glennj** [comment]
> Man that re-order is like impossible to review

Told ya!

> did you do that using an automated tool or by hand? :)

jq has sort commands. 


> That script is awesome... could you spit out the standard deviation across tracks also?  That might be interested in dicsuss in a larger context.

Sure, on Monday.

**Comment by glennj** [comment]
> could you spit out the standard deviation across tracks 

https://exercism-team.slack.com/archives/CARRG4MNC/p1659363468774649

**Comment by glennj** [comment]
rebased to pull in new linked-list exercise in it's proper spot

**Review by joshgoebel — APPROVED** [review]

**Pull request merged**
