### PR TITLE
list-ops: 2 "new" constructors, different signatures

### LINKED ISSUE #113: List-Ops confusion
I was solving list-ops, and I got the error
```none
● append entries to a list and return the new list -> empty lists

ListOps metaclass does not implement 'new()'.

  48 |   do.describe("append entries to a list and return the new list") {
  49 |     do.test("empty lists") {
> 50 |       var list1 = ListOps.new()
  51 |       var list2 = ListOps.new()
  52 |       list1.addAll(list2)
```

I found this confusing because of course `construct new(elements) {...}` exists.

It took me a minute to realize that this is the first time we see a no-args `new()`.

I'll add a new test to the suite.

### PR DESCRIPTION
**Pull request by glennj**
I think this is the first exercise that we overload "new".

closes #113

### CODE REVIEW

**Comment by glennj** [comment]
OK there's several different implementations for this "overloaded constructor":

```wren
class ListOps {
  construct new() {
    _data =[]
  }
  construct new(elements) {
    _data = elems[0..-1]
  }
}
```
```wren
class ListOps {
  construct new() {
    this.init_([])
  }
  construct new(elements) {
    this.init_(elements)
  }
  init_(elems) {
    _data = elems[0..-1]
  }
}
```
```wren
class ListOps {
  static new() {
    return new([])
  }
  construct new(elements) {
    _data = elems[0..-1]
  }
}
```
I think the 3rd one is best.

Adding stub methods kind of pushes the student to a particular solution.

The difficulty for this exercise is relatively high, and it occurs later in the track, so should I rip out the stub methods?

**Comment by joshgoebel** [comment]
> I think the 3rd one is best.

Agreed, this is the typical Wren approach I see... the most complex method has all the logic and then the "simpler" versions just defer up the chain until eventually hitting the FULL method signature... in this case we just have the one jump of course.

**Comment by joshgoebel** [comment]
> so should I rip out the stub methods?

Lets resolve that in the dedicated thread... this could then be merged as-is or it could be held until after we sort that...

**Comment by glennj** [comment]
probably no rush. I like to have at least one community solution for each exercise which is why I solve new exercises quickly. As a student I find other people's solutions very valuable.

**Review by joshgoebel — APPROVED** [review]

**Pull request merged**
